### ISSUE TITLE
IEEEmadC - Submission 

### ISSUE THREAD

**Issue by SangramChavan** [AQaddora/EducationalPlatform#1]
Your apps look's good, nice UI. Can you please add a table to your readme.md? sharing an example below.

Example: App Name (Hyperlink to executable file) | Repo name (Hyperlink to repo) | description (short description of app in few words) | Choose any license e.g. MIT (Hyperlink to Licence)| UK (Location)| Name of members (Hyperlink to Github profiles that contributed to the project) |

**Comment by AQaddora** [comment]
Hello, 
I have updated it. you can take a look now.
